"use client";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";


import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import LoadingScreen from "@/components/LoadingScreen";
import useShowLoader from "@/hooks/useShowLoader";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  const showLoader = useShowLoader();
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        {showLoader && <LoadingScreen />}
        <Navbar />
        <div className="flex-1 flex flex-col">
          {!showLoader && children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
